Repository hyperion-mc/hyperion, pull requests merged in 2024-12, with the labels that each got.

#658 feat: arrow and some raycast changes.
  Cargo.toml
  crates/geometry/src/ray.rs
  crates/hyperion/src/egress/sync_entity_state.rs
  crates/hyperion/src/simulation/blocks/mod.rs
  crates/hyperion/src/simulation/mod.rs
  events/tag/src/command.rs
  events/tag/src/command/shoot.rs
Labels: feat

#661 feat(hyperion)!: hardcoded SystemId → auto SystemOrder
  Cargo.lock
  Cargo.toml
  crates/hyperion-clap/src/lib.rs
  crates/hyperion-command/src/component.rs
  crates/hyperion-command/src/system.rs
  crates/hyperion-gui/src/lib.rs
  crates/hyperion-permission/src/lib.rs
  crates/hyperion/Cargo.toml
  crates/hyperion/src/common/mod.rs
  crates/hyperion/src/common/system_registry.rs
  crates/hyperion/src/egress/mod.rs
  crates/hyperion/src/egress/player_join/mod.rs
  crates/hyperion/src/egress/sync_chunks.rs
  crates/hyperion/src/egress/sync_entity_state.rs
  crates/hyperion/src/ingress/mod.rs
  crates/hyperion/src/lib.rs
  crates/hyperion/src/net/mod.rs
  crates/hyperion/src/simulation/handlers.rs
  crates/hyperion/src/simulation/mod.rs
  crates/system-order/.gitignore
  crates/system-order/Cargo.toml
  crates/system-order/README.md
  crates/system-order/src/lib.rs
  events/tag/src/command/class.rs
  events/tag/src/command/fly.rs
  events/tag/src/command/gui.rs
  events/tag/src/command/raycast.rs
  events/tag/src/command/replace.rs
  events/tag/src/command/shoot.rs
  events/tag/src/command/spawn.rs
  events/tag/src/command/speed.rs
  events/tag/src/command/xp.rs
  events/tag/src/module/attack.rs
  events/tag/src/module/block.rs
  events/tag/src/module/chat.rs
  events/tag/src/module/stats.rs
  events/tag/src/skin.rs
Labels: feat, breaking change

#664 feat(spatial): add BVH spatial indexing
  Cargo.lock
  Cargo.toml
  crates/bvh-region/Cargo.toml
  crates/bvh-region/benches/bvh.rs
  crates/bvh-region/benches/side_by_side.rs
  crates/bvh-region/src/lib.rs
  crates/bvh-region/src/plot.rs
  crates/bvh-region/src/tests.rs
  crates/geometry/src/aabb.rs
  crates/hyperion-proxy/src/cache.rs
  crates/hyperion/Cargo.toml
  crates/hyperion/src/egress/player_join/mod.rs
  crates/hyperion/src/ingress/mod.rs
  crates/hyperion/src/net/mod.rs
  crates/hyperion/src/simulation/mod.rs
  crates/spatial/.gitignore
  crates/spatial/Cargo.toml
  crates/spatial/README.md
  crates/spatial/src/lib.rs
  events/tag/Cargo.toml
  events/tag/src/command/spawn.rs
  events/tag/src/lib.rs
Labels: feat

#666 feat: bows 🏹
  crates/hyperion/src/egress/sync_entity_state.rs
  crates/hyperion/src/simulation/bow.rs
  crates/hyperion/src/simulation/event.rs
  crates/hyperion/src/simulation/handlers.rs
  crates/hyperion/src/simulation/mod.rs
  crates/hyperion/src/storage/event/queue/mod.rs
  events/tag/src/command.rs
  events/tag/src/command/bow.rs
  events/tag/src/lib.rs
  events/tag/src/module.rs
  events/tag/src/module/bow.rs
Labels: feat

#669 feat: show `BowCharging` data in flecs panel
  Cargo.lock
  Cargo.toml
  crates/hyperion/Cargo.toml
  crates/hyperion/src/simulation/bow.rs
  crates/hyperion/src/simulation/handlers.rs
  crates/hyperion/src/simulation/mod.rs
Labels: feat

#670 feat: vanish 💨
  Cargo.lock
  crates/hyperion/src/egress/player_join/mod.rs
  crates/hyperion/src/egress/sync_entity_state.rs
  crates/hyperion/src/simulation/metadata/mod.rs
  events/tag/Cargo.toml
  events/tag/src/command.rs
  events/tag/src/command/vanish.rs
  events/tag/src/lib.rs
  events/tag/src/module.rs
  events/tag/src/module/vanish.rs
Labels: feat

#671 fix(hyperion): general arrow heading
  Cargo.lock
  Cargo.toml
  crates/hyperion-clap/src/lib.rs
  crates/hyperion-proto/Cargo.toml
  crates/hyperion-proto/src/shared.rs
  crates/hyperion/src/common/config.rs
  crates/hyperion/src/egress/mod.rs
  crates/hyperion/src/egress/player_join/mod.rs
  crates/hyperion/src/egress/sync_chunks.rs
  crates/hyperion/src/egress/sync_entity_state.rs
  crates/hyperion/src/net/mod.rs
  crates/hyperion/src/simulation/blocks/frame.rs
  crates/hyperion/src/simulation/blocks/loader/mod.rs
  crates/hyperion/src/simulation/blocks/manager.rs
  crates/hyperion/src/simulation/blocks/mod.rs
  crates/hyperion/src/simulation/mod.rs
  events/tag/Cargo.toml
  events/tag/src/command/class.rs
  events/tag/src/command/fly.rs
  events/tag/src/command/replace.rs
  events/tag/src/command/speed.rs
  events/tag/src/module/spawn.rs
  events/tag/src/skin.rs
Labels: fix

#672 fix: packet ordering in observers
  crates/hyperion/src/egress/sync_entity_state.rs
  crates/hyperion/src/simulation/mod.rs
  crates/system-order/src/lib.rs
Labels: fix

#675 fix: consistent packet ordering in `sync_entity_state`
  crates/hyperion/src/egress/sync_entity_state.rs
Labels: fix

#690 ci: merge dependabot.yml
  .github/dependabot.yml
  dependabot.yml
Labels: ci

#691 fix: position syncing
  crates/hyperion/src/lib.rs
Labels: fix

#695 feat(core): send more combat related packets
  crates/hyperion/src/simulation/metadata/living_entity.rs
  events/tag/src/module/attack.rs
Labels: feat

#697 feat(tool): add packet inspector tool
  Cargo.lock
  Cargo.toml
  tools/packet-inspector/Cargo.toml
  tools/packet-inspector/README.md
  tools/packet-inspector/build.rs
  tools/packet-inspector/extracted/packets.json
  tools/packet-inspector/src/app.rs
  tools/packet-inspector/src/app/connection.rs
  tools/packet-inspector/src/app/filter.rs
  tools/packet-inspector/src/app/hex_viewer.rs
  tools/packet-inspector/src/app/packet_list.rs
  tools/packet-inspector/src/app/text_viewer.rs
  tools/packet-inspector/src/lib.rs
  tools/packet-inspector/src/main.rs
  tools/packet-inspector/src/main_cli.rs
  tools/packet-inspector/src/packet_io.rs
  tools/packet-inspector/src/packet_registry.rs
  tools/packet-inspector/src/shared_state.rs
  tools/packet-inspector/src/tri_checkbox.rs
Labels: feat

#699 fix: damage tilt
  events/tag/src/module/attack.rs
Labels: fix

#705 refactor: restructure .gitignore
  .gitignore
Labels: refactor

#696 feat(core): physics
  crates/hyperion-inventory/src/lib.rs
  crates/hyperion/src/egress/sync_entity_state.rs
  crates/hyperion/src/simulation/handlers.rs
  crates/hyperion/src/simulation/metadata/mod.rs
  crates/hyperion/src/simulation/mod.rs
  events/tag/src/command/shoot.rs
  events/tag/src/command/spawn.rs
  events/tag/src/module/attack.rs
  events/tag/src/module/bow.rs
Labels: feat

#709 ci: add docker build
  .dockerignore
  .github/workflows/build.yml
  Dockerfile
Labels: ci

#710 ci: build & publish release image
  .github/workflows/build.yml
  .github/workflows/publish.yml
  Dockerfile
  docker-compose.release.yml
  docker-compose.yml
Labels: ci

#711 ci: build with arm64 support
  .github/workflows/publish.yml
Labels: ci

#713 ci: publish amd64 and arm64 images
  .github/workflows/publish.yml
Labels: ci

#715 ci: publish using depot
  .github/workflows/publish.yml
Labels: ci

#716 ci: depot (attempt 2)
  .github/workflows/publish.yml
Labels: ci

#717 ci: depot (attempt 3)
  .github/workflows/publish.yml
Labels: ci

#718 ci: don't use target-cpu native
  .dockerignore
  Dockerfile
Labels: ci

#714 feat(spatial,bvh): add get_collisions
  crates/bvh-region/src/lib.rs
  crates/spatial/src/lib.rs
Labels: feat

#722 refactor: bind edition, version to workspace
  crates/bvh-region/Cargo.toml
  crates/geometry/Cargo.toml
  crates/hyperion-clap-macros/Cargo.toml
  crates/hyperion-clap/Cargo.toml
  crates/hyperion-command/Cargo.toml
  crates/hyperion-crafting/Cargo.toml
  crates/hyperion-event-macros/Cargo.toml
  crates/hyperion-gui/Cargo.toml
  crates/hyperion-inventory/Cargo.toml
  crates/hyperion-item/Cargo.toml
  crates/hyperion-item/src/builder.rs
  crates/hyperion-minecraft-proto/Cargo.toml
  crates/hyperion-nerd-font/Cargo.toml
  crates/hyperion-palette/Cargo.toml
  crates/hyperion-permission/Cargo.toml
  crates/hyperion-proto/Cargo.toml
  crates/hyperion-proto/rustfmt.toml
  crates/hyperion-proxy/Cargo.toml
  crates/hyperion-rank-tree/Cargo.toml
  crates/hyperion-rank-tree/src/lib.rs
  crates/hyperion-scheduled/Cargo.toml
  crates/hyperion-stats/Cargo.toml
  crates/hyperion-text/Cargo.toml
  crates/hyperion-utils/Cargo.toml
  crates/hyperion/Cargo.toml
  crates/simd-utils/Cargo.toml
  crates/simd-utils/src/lib.rs
  crates/spatial/Cargo.toml
  crates/spatial/src/lib.rs
  crates/system-order/Cargo.toml
  crates/system-order/src/lib.rs
  events/tag/Cargo.toml
Labels: refactor

#723 fix(bvh-region): `get_closest` now returns the correct closest element
  Cargo.lock
  Cargo.toml
  crates/bvh-region/Cargo.toml
  crates/bvh-region/src/build.rs
  crates/bvh-region/src/lib.rs
  crates/bvh-region/src/node.rs
  crates/bvh-region/src/query.rs
  crates/bvh-region/src/query/closest.rs
  crates/bvh-region/src/utils.rs
  crates/bvh-region/tests/simple.rs
  crates/geometry/src/aabb.rs
  crates/spatial/src/lib.rs
Labels: fix

#724 perf(bvh-region): more efficient range query
  crates/bvh-region/src/lib.rs
  crates/bvh-region/src/query.rs
  crates/bvh-region/src/query/closest.rs
  crates/bvh-region/src/query/range.rs
  crates/bvh-region/tests/simple.rs
  crates/geometry/src/aabb.rs
  crates/spatial/src/lib.rs
Labels: perf

#726 ci: lint with Dockerfile
  .github/workflows/build.yml
  .github/workflows/lint.yml
  Dockerfile
Labels: ci

#727 fix: use new org for docker images
  docker-compose.yml
Labels: fix

#728 feat: clean up docker configuration
  Dockerfile
  README.md
  docker-compose.yml
Labels: feat

#730 ci: use `--frozen`
  Dockerfile
Labels: ci

#731 docs: create FUNDING.yml
  .github/FUNDING.yml
Labels: docs

#725 feat(bvh-region): add raycast query
  Cargo.lock
  crates/bvh-region/Cargo.toml
  crates/bvh-region/src/query.rs
  crates/bvh-region/src/query/closest.rs
  crates/bvh-region/src/query/ray.rs
  crates/bvh-region/src/utils.rs
  crates/bvh-region/tests/simple.rs
  crates/geometry/Cargo.toml
  crates/geometry/src/aabb.rs
  crates/geometry/src/ray.rs
Labels: feat

#720 feat(core): Entity To Entity Raycasting.
  Cargo.lock
  crates/geometry/src/ray.rs
  crates/hyperion/src/egress/sync_entity_state.rs
  crates/hyperion/src/simulation/blocks/mod.rs
  crates/spatial/Cargo.toml
  crates/spatial/src/lib.rs
  events/tag/src/command/raycast.rs
Labels: feat

#736 feat: `Hyperion` is now a module
  Cargo.lock
  crates/hyperion/src/common/mod.rs
  crates/hyperion/src/lib.rs
  events/tag/Cargo.toml
  events/tag/src/lib.rs
  events/tag/src/main.rs
Labels: feat

#737 feat(core): remove `AddressModule`, use observer
  crates/hyperion/src/lib.rs
  events/tag/src/lib.rs
Labels: feat

#739 fix: #738
  crates/hyperion/src/lib.rs
  events/tag/src/lib.rs
Labels: fix

#740 feat(system-order): automatically re-calculate
  Cargo.lock
  crates/hyperion/src/lib.rs
  crates/system-order/src/lib.rs
  events/tag/Cargo.toml
  events/tag/src/lib.rs
Labels: feat

#741 docs: add Minecraft server join link
  README.md
Labels: docs

#743 docs(core): `SpatialIndex` index entities with the `Spatial` component
  crates/spatial/src/lib.rs
Labels: docs

#742 refactor: restructure to add arrow test
  Cargo.lock
  Cargo.toml
  crates/hyperion-genmap/.gitignore
  crates/hyperion-genmap/Cargo.toml
  crates/hyperion-genmap/README.md
  crates/hyperion-genmap/src/lib.rs
  crates/hyperion/Cargo.toml
  crates/hyperion/run/config.toml
  crates/hyperion/src/simulation/entity_kind.rs
  crates/hyperion/src/simulation/mod.rs
  crates/hyperion/tests/arrows.rs
  events/tag/Cargo.toml
  events/tag/src/lib.rs
Labels: refactor

#745 feat: default `AppId` -> simpler integration tests
  crates/hyperion-genmap/src/lib.rs
  crates/hyperion-utils/src/lib.rs
  crates/hyperion/tests/arrows.rs
Labels: feat

#747 test: add `TestModule` for easier testing
  crates/hyperion-genmap/src/lib.rs
  crates/hyperion/tests/entity.rs
Labels: test

#748 ci: add cargo doc
  Dockerfile
Labels: ci

#749 fix: start `flecs.dev/explorer` server
  Dockerfile
  events/tag/src/lib.rs
Labels: fix

#750 ci: improve speeds
  Dockerfile
Labels: ci

#751 feat: add empty `Block` loader
  Cargo.lock
  crates/hyperion/Cargo.toml
  crates/hyperion/src/lib.rs
  crates/hyperion/src/simulation/blocks/loader/mod.rs
  crates/hyperion/src/simulation/blocks/mod.rs
  crates/hyperion/tests/entity.rs
Labels: feat

#753 perf: use alloc zeroed to implement calloc
  crates/hyperion/src/alloc.rs
Labels: perf

#754 test: add spatial query
  Cargo.lock
  crates/bvh-region/src/query/ray.rs
  crates/bvh-region/tests/simple.rs
  crates/geometry/src/ray.rs
  crates/hyperion/Cargo.toml
  crates/hyperion/src/simulation/mod.rs
  crates/hyperion/tests/entity.rs
  crates/hyperion/tests/spatial.rs
  crates/spatial/src/lib.rs
Labels: test

#755 ci: improve parallelism
  Dockerfile
Labels: ci

#752 fix: initialize scratch buffer
  crates/hyperion/src/lib.rs
  crates/hyperion/src/net/encoder/mod.rs
Labels: fix

#756 refactor: remove unused `alloc.rs`
  crates/hyperion/Cargo.toml
  crates/hyperion/src/alloc.rs
Labels: refactor

#757 chore: update `Cargo.lock`
  Cargo.lock
Labels: chore

#758 refactor: clean up code
  Cargo.lock
  Cargo.toml
  Dockerfile
  crates/hyperion/Cargo.toml
  crates/hyperion/src/lib.rs
  events/tag/src/lib.rs
Labels: refactor

#702 feat: respawn
  Cargo.lock
  Cargo.toml
  crates/hyperion-respawn/.gitignore
  crates/hyperion-respawn/Cargo.toml
  crates/hyperion-respawn/README.md
  crates/hyperion-respawn/src/lib.rs
  crates/hyperion/src/lib.rs
  crates/hyperion/src/simulation/event.rs
  crates/hyperion/src/simulation/handlers.rs
  crates/hyperion/src/simulation/metadata/mod.rs
  crates/hyperion/src/storage/event/queue/mod.rs
  events/tag/Cargo.toml
  events/tag/src/lib.rs
  events/tag/src/module/attack.rs
  events/tag/src/module/regeneration.rs
Labels: feat

#762 feat(rust-mc-bot): init
  Cargo.lock
  Cargo.toml
  tools/rust-mc-bot/.gitignore
  tools/rust-mc-bot/Cargo.lock
  tools/rust-mc-bot/Cargo.toml
  tools/rust-mc-bot/LICENSE
  tools/rust-mc-bot/README.md
  tools/rust-mc-bot/src/lib.rs
  tools/rust-mc-bot/src/main.rs
  tools/rust-mc-bot/src/net.rs
  tools/rust-mc-bot/src/packet_processors.rs
  tools/rust-mc-bot/src/packet_utils.rs
  tools/rust-mc-bot/src/states/login.rs
  tools/rust-mc-bot/src/states/mod.rs
  tools/rust-mc-bot/src/states/play.rs
  tools/rust-mc-bot/src/states/status.rs
Labels: feat

#763 refactor: remove unused `Cargo.lock` file
  Cargo.lock
  tools/rust-mc-bot/Cargo.lock
Labels: refactor

#764 ci: build for antithesis
  .github/workflows/publish.yml
  Dockerfile
  Dockerfile-antithesis
  antithesis/docker-compose.yml
  libvoidstar.so
Labels: ci

#765 ci: fix publish workflow
  .github/workflows/publish.yml
Labels: ci

#766 ci: attempt fix (again eek)
  .github/workflows/publish.yml
Labels: ci

#767 ci: speedup; use --frozen, --all-features for nextest
  Dockerfile
Labels: ci

#768 ci: separate antithesis cache
  Dockerfile
Labels: ci

#773 feat: antitheis bot
  Cargo.lock
  Cargo.toml
  Dockerfile
  antithesis/docker-compose.yml
  tools/antithesis-bot/Cargo.toml
  tools/antithesis-bot/src/bot.rs
  tools/antithesis-bot/src/lib.rs
  tools/antithesis-bot/src/main.rs
Labels: feat

#774 ci: use ubuntu-latest
  .github/workflows/lint.yml
Labels: ci

#775 ci: publish antithesis-bot
  .github/workflows/publish.yml
Labels: ci

#776 fix: linking error building antithesis-bot
  Dockerfile
Labels: fix

#777 fix: antithesis-bot build
  .gitignore
  Cargo.lock
  Cargo.toml
  Dockerfile
  tools/antithesis-bot/Cargo.toml
  tools/antithesis-bot/src/bot.rs
Labels: fix

#778 fix: antithesis-bot include libvoidstar.so
  Dockerfile
Labels: fix

#779 ci: add benching
  .github/workflows/bench.yml
  Cargo.lock
  Cargo.toml
  crates/geometry/Cargo.toml
  crates/geometry/benches/general.rs
  crates/geometry/build.rs
Labels: ci

#782 ci: use later version of dawidd6/action-download-artifact
  .github/workflows/bench.yml
Labels: ci

#785 feat: `add antithesis-sdk::antithesis_init`
  tools/antithesis-bot/src/lib.rs
Labels: feat

#786 feat: use libvoidstar.so properly
  Dockerfile
  antithesis/docker-compose.yml
  tools/antithesis-bot/src/lib.rs
  tools/antithesis-bot/src/main.rs
Labels: feat

#787 fix(antithesis): docker compose
  Dockerfile
  antithesis/docker-compose.yml
  tools/antithesis-bot/src/lib.rs
  tools/antithesis-bot/src/main.rs
Labels: fix

#788 ci: speed up
  Dockerfile
Labels: ci

#792 feat: color chat based on team
  events/tag/src/module/chat.rs
Labels: feat

#791 feat: respawn near ally and distribute xp
  crates/hyperion-respawn/src/lib.rs
  crates/hyperion/src/simulation/handlers.rs
  crates/hyperion/src/storage/event/sync.rs
  events/tag/src/lib.rs
  events/tag/src/module/attack.rs
  events/tag/src/module/spawn.rs
Labels: feat

#795 fix: don't change skin
  Cargo.lock
  crates/hyperion-rank-tree/Cargo.toml
  crates/hyperion-rank-tree/src/lib.rs
  crates/hyperion-rank-tree/src/skin.rs
  crates/hyperion-rank-tree/src/skin/archer.toml
  crates/hyperion-rank-tree/src/skin/blue/knight.toml
  crates/hyperion-rank-tree/src/skin/builder.toml
  crates/hyperion-rank-tree/src/skin/excavator.toml
  crates/hyperion-rank-tree/src/skin/green/knight.toml
  crates/hyperion-rank-tree/src/skin/knight.toml
  crates/hyperion-rank-tree/src/skin/mage.toml
  crates/hyperion-rank-tree/src/skin/miner.toml
  crates/hyperion-rank-tree/src/skin/red/knight.toml
  crates/hyperion-rank-tree/src/skin/stick.toml
  crates/hyperion-rank-tree/src/skin/swordsman.toml
  crates/hyperion-rank-tree/src/skin/yellow/knight.toml
  events/tag/src/command/class.rs
Labels: fix

#796 fix: some block related fixes & changes
  crates/hyperion/src/ingress/mod.rs
  crates/hyperion/src/simulation/event.rs
  crates/hyperion/src/simulation/handlers.rs
  crates/hyperion/src/storage/event/queue/mod.rs
  events/tag/src/command/replace.rs
Labels: fix
