Repository hyperion-mc/hyperion, pull requests merged in 2025-04, with the labels that each got.

#880 feat: tag starts proxy
  .github/workflows/integration.yml
  Cargo.lock
  Cargo.toml
  crates/hyperion-proxy-module/Cargo.toml
  crates/hyperion-proxy-module/README.md
  crates/hyperion-proxy-module/src/lib.rs
  crates/hyperion-proxy/src/lib.rs
  events/tag/Cargo.toml
  events/tag/src/lib.rs
Labels: feat

#883 feat: use single threaded flecs
  crates/hyperion/src/egress/mod.rs
  crates/hyperion/src/egress/sync_chunks.rs
  crates/hyperion/src/egress/sync_entity_state.rs
  crates/hyperion/src/ingress/mod.rs
  crates/hyperion/src/lib.rs
  crates/hyperion/src/simulation/inventory.rs
  crates/hyperion/src/simulation/metadata/mod.rs
  events/tag/src/module/attack.rs
  events/tag/src/module/block.rs
  events/tag/src/module/bow.rs
  events/tag/src/module/chat.rs
  events/tag/src/module/regeneration.rs
  events/tag/src/module/stats.rs
  events/tag/src/module/vanish.rs
Labels: feat

#884 fix(inventory): do not extend slot lifetimes
  crates/hyperion/src/simulation/inventory.rs
Labels: fix

#886 docs: add governance and code of conduct
  CODE_OF_CONDUCT.md
  GOVERNANCE.md
Labels: docs

#893 chore(governance): define process for changing governance
  GOVERNANCE.md
Labels: chore
