Repository hyperion-mc/hyperion, pull requests merged in 2025-03, with the labels that each got.

#831 fix: better player movement handling
  Cargo.lock
  crates/hyperion-respawn/src/lib.rs
  crates/hyperion/src/egress/player_join/mod.rs
  crates/hyperion/src/egress/sync_entity_state.rs
  crates/hyperion/src/simulation/blocks/mod.rs
  crates/hyperion/src/simulation/event.rs
  crates/hyperion/src/simulation/handlers.rs
  crates/hyperion/src/simulation/mod.rs
  crates/hyperion/src/storage/event/queue/mod.rs
  events/tag/src/command/fly.rs
  events/tag/src/command/speed.rs
  events/tag/src/lib.rs
  events/tag/src/module.rs
  events/tag/src/module/attack.rs
  events/tag/src/module/damage.rs
Labels: fix

#857 fix: use ItemKind equippable attribute instead of hardcoding
  Cargo.lock
  crates/hyperion-inventory/Cargo.toml
  crates/hyperion-inventory/src/lib.rs
Labels: fix

#850 ci: public arm64 docker image
  .github/workflows/publish.yml
Labels: ci

#859 feat: only run bots if `docker compose --profile bot up`
  .github/workflows/integration.yml
  docker-compose.yml
Labels: feat

#860 feat: use environment variables to configure
  .dockerignore
  Cargo.lock
  Dockerfile
  crates/hyperion-proxy/Cargo.toml
  crates/hyperion-proxy/src/main.rs
  docker-compose.yml
  events/tag/Cargo.toml
  events/tag/src/main.rs
  tools/rust-mc-bot/Cargo.toml
  tools/rust-mc-bot/src/main.rs
Labels: feat

#863 chore: update deps
  Cargo.lock
Labels: chore

#864 feat: update to flecs with safety checks
  Cargo.lock
  crates/hyperion/Cargo.toml
  crates/hyperion/src/egress/sync_entity_state.rs
  crates/hyperion/src/ingress/mod.rs
  crates/hyperion/src/net/proxy.rs
  crates/hyperion/src/simulation/handlers.rs
  crates/hyperion/src/simulation/metadata/mod.rs
  justfile
Labels: feat

#869 chore: update kanal version
  Cargo.lock
  Cargo.toml
  crates/hyperion-proxy/src/data.rs
  crates/hyperion/src/common/runtime.rs
  crates/hyperion/src/storage/thread_local.rs
Labels: chore

#870 feat: update latest flecs
  Cargo.lock
  crates/hyperion/src/ingress/mod.rs
Labels: feat

#871 docs: update README
  README.md
Labels: docs

#874 docs: fix docs link
  README.md
Labels: docs
