Repository hyperion-mc/hyperion, pull requests merged in 2025-01, with the labels that each got.

#801 feat: support nix
  .envrc
  .gitignore
  Cargo.lock
  Cargo.toml
  Dockerfile-antithesis
  antithesis/docker-compose.yml
  crates/hyperion/src/net/mod.rs
  flake.lock
  flake.nix
Labels: feat

#803 ci: cleanup
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  Dockerfile
Labels: ci

#804 fix: docs github link
  docs/.vitepress/config.mts
Labels: fix

#771 feat: packet handling functions
  Cargo.lock
  Cargo.toml
  crates/hyperion-clap/src/lib.rs
  crates/hyperion-command/Cargo.toml
  crates/hyperion-command/src/component.rs
  crates/hyperion-command/src/system.rs
  crates/hyperion-event-macros/src/lib.rs
  crates/hyperion-gui/Cargo.toml
  crates/hyperion-gui/src/lib.rs
  crates/hyperion-item/Cargo.toml
  crates/hyperion-item/src/lib.rs
  crates/hyperion-packet-macros/.gitignore
  crates/hyperion-packet-macros/Cargo.toml
  crates/hyperion-packet-macros/README.md
  crates/hyperion-packet-macros/src/lib.rs
  crates/hyperion-respawn/src/lib.rs
  crates/hyperion-utils/Cargo.toml
  crates/hyperion-utils/src/lib.rs
  crates/hyperion-utils/src/lifetime.rs
  crates/hyperion/Cargo.toml
  crates/hyperion/src/egress/mod.rs
  crates/hyperion/src/ingress/mod.rs
  crates/hyperion/src/lib.rs
  crates/hyperion/src/net/mod.rs
  crates/hyperion/src/simulation/event.rs
  crates/hyperion/src/simulation/handlers.rs
  crates/hyperion/src/simulation/mod.rs
  crates/hyperion/src/simulation/packet.rs
  crates/hyperion/src/storage/event/queue/event_queue.rs
  crates/hyperion/src/storage/event/queue/mod.rs
  crates/hyperion/src/storage/event/sync.rs
  events/tag/src/module/attack.rs
  events/tag/src/module/chat.rs
Labels: feat

#810 fix: rust-mc-bot for windows
  tools/rust-mc-bot/src/lib.rs
  tools/rust-mc-bot/src/main.rs
Labels: fix

#811 ci: add windows
  .github/workflows/ci.yml
Labels: ci

#812 ci(codecov): do not fail if no % difference
  .github/codecov.yml
Labels: ci

#814 ci(publish): only build amd64 for now
  .github/workflows/publish.yml
Labels: ci

#815 chore: add cname
  CNAME
Labels: chore

#817 chore: move to pnpm
  .github/workflows/deploy.yml
  package-lock.json
  pnpm-lock.yaml
Labels: chore

#818 fix: vitepress build
  docs/.vitepress/theme/components/GithubSnippet.vue
  package.json
  pnpm-lock.yaml
Labels: fix

#772 feat: arrow entity handling and damage.
  Cargo.lock
  Cargo.toml
  crates/geometry/src/aabb.rs
  crates/geometry/src/ray.rs
  crates/hyperion/Cargo.toml
  crates/hyperion/src/egress/sync_entity_state.rs
  crates/hyperion/src/lib.rs
  crates/hyperion/src/simulation/animation.rs
  crates/hyperion/src/simulation/blocks/mod.rs
  crates/hyperion/src/simulation/bow.rs
  crates/hyperion/src/simulation/event.rs
  crates/hyperion/src/simulation/handlers.rs
  crates/hyperion/src/simulation/mod.rs
  crates/hyperion/src/spatial/mod.rs
  crates/hyperion/src/storage/event/queue/mod.rs
  crates/hyperion/tests/collision.rs
  crates/hyperion/tests/entity.rs
  crates/hyperion/tests/spatial.rs
  crates/spatial/.gitignore
  crates/spatial/Cargo.toml
  crates/spatial/README.md
  events/tag/Cargo.toml
  events/tag/src/command/raycast.rs
  events/tag/src/lib.rs
  events/tag/src/module/bow.rs
Labels: feat

#820 fix: remove PluginMessage
  crates/hyperion/src/simulation/event.rs
  crates/hyperion/src/simulation/handlers.rs
  crates/hyperion/src/storage/event/queue/mod.rs
Labels: fix

#822 chore: update vitepress deps
  package.json
  pnpm-lock.yaml
Labels: chore

#793 feat(inventory): Tebarem/inventory
  Cargo.lock
  crates/hyperion-gui/Cargo.toml
  crates/hyperion-gui/src/lib.rs
  crates/hyperion-inventory/Cargo.toml
  crates/hyperion-inventory/src/action.rs
  crates/hyperion-inventory/src/lib.rs
  crates/hyperion-inventory/src/parser.rs
  crates/hyperion-item/src/lib.rs
  crates/hyperion-rank-tree/src/inventory.rs
  crates/hyperion/src/egress/sync_entity_state.rs
  crates/hyperion/src/lib.rs
  crates/hyperion/src/simulation/entity_kind.rs
  crates/hyperion/src/simulation/event.rs
  crates/hyperion/src/simulation/handlers.rs
  crates/hyperion/src/simulation/inventory.rs
  crates/hyperion/src/simulation/mod.rs
  crates/hyperion/src/storage/event/queue/mod.rs
  events/tag/src/command.rs
  events/tag/src/command/chest.rs
  events/tag/src/command/gui.rs
  events/tag/src/lib.rs
  events/tag/src/module/attack.rs
  events/tag/src/module/block.rs
  events/tag/src/module/bow.rs
Labels: feat

#830 fix(blocks): return void air above height limit
  crates/hyperion/src/simulation/blocks/mod.rs
Labels: fix

#829 fix(bvh-region): get_closest on empty bvh
  crates/bvh-region/src/query/closest.rs
  crates/bvh-region/tests/simple.rs
Labels: fix

#828 fix: respawning without teammates
  events/tag/src/module/attack.rs
  events/tag/src/module/spawn.rs
Labels: fix

#826 feat: add critical hits
  events/tag/src/module/attack.rs
Labels: feat

#825 perf: raycasting geometry +50%
  crates/geometry/src/aabb.rs
Labels: perf
