Repository hyperion-mc/hyperion, pull requests merged in 2025-05, with the labels that each got.

#894 fix: use saturating_add on received_movement_packets
  crates/hyperion/src/simulation/handlers.rs
Labels: fix

#895 fix(ingress): don't fetch skins for players without uuids
  crates/hyperion/src/ingress/mod.rs
Labels: fix

#899 refactor: update flecs
  Cargo.lock
  crates/hyperion-clap/src/lib.rs
  crates/hyperion-permission/src/lib.rs
  crates/hyperion-respawn/src/lib.rs
  crates/hyperion/src/egress/mod.rs
  crates/hyperion/src/egress/player_join/mod.rs
  crates/hyperion/src/egress/stats.rs
  crates/hyperion/src/egress/sync_chunks.rs
  crates/hyperion/src/egress/sync_entity_state.rs
  crates/hyperion/src/ingress/mod.rs
  crates/hyperion/src/lib.rs
  crates/hyperion/src/simulation/command.rs
  crates/hyperion/src/simulation/handlers.rs
  crates/hyperion/src/simulation/inventory.rs
  crates/hyperion/src/simulation/metadata/mod.rs
  crates/hyperion/src/simulation/mod.rs
  crates/hyperion/src/spatial/mod.rs
  crates/hyperion/tests/collision.rs
  crates/hyperion/tests/entity.rs
  crates/hyperion/tests/spatial.rs
  crates/system-order/src/lib.rs
  events/tag/src/command/class.rs
  events/tag/src/command/fly.rs
  events/tag/src/command/spawn.rs
  events/tag/src/command/xp.rs
  events/tag/src/lib.rs
  events/tag/src/module/attack.rs
  events/tag/src/module/block.rs
  events/tag/src/module/bow.rs
  events/tag/src/module/spawn.rs
  events/tag/src/module/vanish.rs
Labels: refactor

#889 fix: malformed packet crash
  crates/hyperion-proto/src/server_to_proxy.rs
  crates/hyperion-proxy/src/cache.rs
  crates/hyperion-proxy/src/data.rs
  crates/hyperion-proxy/src/egress.rs
  crates/hyperion-proxy/src/player.rs
  crates/hyperion/src/egress/player_join/mod.rs
  crates/hyperion/src/ingress/mod.rs
  crates/hyperion/src/net/mod.rs
Labels: fix

#902 docs: remove broken Discord invite
  README.md
Labels: docs

#900 fix: inventory slot bounds check
  crates/hyperion-inventory/src/lib.rs
Labels: fix, codex
